version: "3.7"
services: 
    # Service API
    api: 
        build: ./api
        image: api:latest
        ports: 
            - "5000:5000"
        volumes: 
            - ./api:/usr/src/app/api
        depends_on:  
            - mongo
        command: npm run dev

    # Service React
    myreact: 
        build: ./myreact
        image: myreact:latest
        ports: 
            - "4000:4000"
        volumes: 
            - ./myreact:/usr/src/app/myreact
        links: 
            - api
        command: npm run start

    # Service mongo
    mongo: 
        image: mongo:latest
        ports: 
            - "27017:27017"
